"""Place to specify target files for the workflow.
The corresponding config file for the project is written under `configfile`."""

configfile: "config/template.yaml"
include: "main.smk"

rule all:
    """Generate target files. This rule runs automatically when Snakefile is run.
    Add or modify the paths under `input` to change the target files generated by snakemake.
    """
    input:
        # Input for generating README.md file
        config["target_files"],
        # Include any other target files below. Can also use variable names from `shortcuts.smk`
        
