---

# Reference genome, which should be placed in this same directory
# Name is just for user understanding.
ref: ../macaque/ref/Mmul_10.fna.gz
#ref: /data/RHESUS/ref/Mmul_10.fasta

# If reference genome isn't downloaded, change to appropriate address to download
ref_address: ftp.ncbi.nlm.nih.gov/genomes/refseq/vertebrate_mammalian/Macaca_mulatta/latest_assembly_versions/GCF_003339765.1_Mmul_10/GCF_003339765.1_Mmul_10_genomic.fna.gz

# Full path to FASTQ data
dataset_path: /data/RHESUS/FASTQ/WES/combined/

# Path to deposit output files
output_path: ../macaque
