---
# Project directories to deposit output files
results: results/Mmul_10/
log: log/Mmul_10/

ref:
  # If reference genome isn't downloaded, change to appropriate address to download
  address: ftp.ncbi.nlm.nih.gov/genomes/refseq/vertebrate_mammalian/Macaca_mulatta/latest_assembly_versions/GCF_003339765.1_Mmul_10/GCF_003339765.1_Mmul_10_genomic.fna.gz
  species: macaca_mulatta

# Path to VCF for base_recalibration step
vcf: results/Mmul_10/ref/Mmul_10.vcf.gz
map: results/Mmul_10/ref/remapping.tsv

VQSR:
  # VCFs for truth and training data for VQSR
  truth_vcf: results/Mmul_10/ref/mult_obs_Mmul_10.vcf.gz
  training_vcf: results/Mmul_10/ref/sing_obs_Mmul_10.vcf.gz

lcmlkin:
  # .txt file of founders
  founders: ''
  vcf: ''

plink:
  # PEDSYS-generated pedigree
  pedigree: ''

admixture:
  # Must have same name before .pop suffix as other PLINK input files to supervised admixture
  pop: ''

population:
  map: ''
  effective_size: 80000

AIMs:
  # Frequency below which to not consider as an AIM.
  # Must be greater than 0.5, perferably as close to 0.9999 while still providing variants.
  threshold: 0.85

# Path to each input FASTQ file
data:
- /data/RHESUS/FASTQ/GBS/rhesus_GBS_demultiplex_output_2019043/GBS30618_2
- /data/RHESUS/FASTQ/GBS/rhesus_GBS_demultiplex_output_2019043/GBS30651_2
- /data/RHESUS/FASTQ/GBS/rhesus_GBS_demultiplex_output_2019043/GBS30739_2
